# Generated by Django 5.2 on 2025-05-02 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image'), ('text', 'Text'), ('link', 'External Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('text_content', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='studymaterials.studyweek')),
            ],
        ),
    ]
