# Generated by Django 5.2 on 2025-05-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_center_unique_together'),
        ('studymaterials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.teacherprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyweek',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_weeks', to='accounts.teacherprofile'),
            preserve_default=False,
        ),
    ]
