# Generated by Django 5.2 on 2025-05-02 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_grades'),
        ('studymaterials', '0002_studymaterial_teacher_studyweek_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.grade'),
            preserve_default=False,
        ),
    ]
