# Generated by Django 5.2 on 2025-06-22 18:37

import django.db.models.deletion
import django.utils.timezone
import studymaterials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_session_token'),
        ('studymaterials', '0003_studymaterial_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-date_created', 'title']},
        ),
        migrations.AlterModelOptions(
            name='studyweek',
            options={'ordering': ['-date_created', 'title']},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='grade',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the study material was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyweek',
            name='centers',
            field=models.ManyToManyField(help_text='Centers that can access this study week', related_name='study_weeks', to='accounts.center'),
        ),
        migrations.AddField(
            model_name='studyweek',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the study week was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyweek',
            name='grade',
            field=models.ForeignKey(default=1, help_text='Grade this study week is assigned to', on_delete=django.db.models.deletion.CASCADE, to='accounts.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL for Video or Link type materials'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Upload file for PDF, Video, or Image types', null=True, upload_to=studymaterials.models.study_material_upload_path),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='text_content',
            field=models.TextField(blank=True, help_text='Text content for Text type materials'),
        ),
        migrations.AlterUniqueTogether(
            name='studyweek',
            unique_together={('teacher', 'title')},
        ),
    ]
