# Generated by Django 5.2 on 2025-08-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterials', '0004_alter_studymaterial_options_alter_studyweek_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyweek',
            unique_together=set(),
        ),
    ]
