# Generated by Django 5.2 on 2025-07-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_session_token'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='has_homework',
            field=models.BooleanField(default=False, verbose_name='Has Homework'),
        ),
        migrations.AddField(
            model_name='session',
            name='has_test',
            field=models.BooleanField(default=False, verbose_name='Has Test'),
        ),
        migrations.CreateModel(
            name='SessionHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_records', to='session.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_homework', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Session Homework',
                'verbose_name_plural': 'Session Homework Records',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
