# Generated by Django 5.2 on 2025-08-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_has_homework_session_has_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontestscore',
            name='max_score',
        ),
        migrations.AddField(
            model_name='session',
            name='test_max_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Test Max Score'),
        ),
    ]
