# Generated by Django 5.2 on 2025-05-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacherprofile_amount_paid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='center',
            unique_together={('name', 'teacher')},
        ),
    ]
