# Generated by Django 5.2 on 2025-05-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_center_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='grades',
            field=models.ManyToManyField(related_name='teachers', to='accounts.grade'),
        ),
    ]
