# Generated by Django 5.2 on 2025-06-05 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='assistantprofile',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.center'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
