# Generated by Django 5.2 on 2025-06-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_added_by_studentprofile_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
