# Generated by Django 5.2 on 2025-08-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
