# Generated by Django 5.2 on 2025-07-08 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_session_token'),
        ('quizzes', '0002_quiz_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='marks_obtained',
            new_name='points_earned',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='created_by',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='is_completed',
            new_name='is_submitted',
        ),
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='submitted_at',
            new_name='start_time',
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit_minutes',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, help_text='Answer for short answer questions', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, help_text='Selected choices for MCQ questions', to='quizzes.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Is this the correct answer?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(help_text='The choice text', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the question', null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='The question content'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='QuizCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.center')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Center Access',
                'verbose_name_plural': 'Quiz Center Access',
                'unique_together': {('quiz', 'center')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='centers',
            field=models.ManyToManyField(through='quizzes.QuizCenter', to='accounts.center'),
        ),
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_minutes', models.PositiveIntegerField(default=0, help_text='Duration in minutes (0 = no time limit)')),
                ('score_visibility', models.CharField(choices=[('immediate', 'Immediately after submission'), ('after_close', 'After quiz is closed'), ('manual', 'Manually by teacher/assistant')], default='after_close', max_length=20)),
                ('answers_visibility', models.CharField(choices=[('immediate', 'Immediately after submission'), ('after_close', 'After quiz is closed'), ('manual', 'Manually by teacher/assistant')], default='after_close', max_length=20)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='quizzes.quiz')),
            ],
        ),
    ]
