# Generated by Django 5.2 on 2025-07-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_session_token'),
        ('quizzes', '0003_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, help_text='Selected choices for MCQ questions', related_name='answers', to='quizzes.choice'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='accounts.grade'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='accounts.teacherprofile'),
        ),
    ]
