# Generated by Django 5.2 on 2025-08-07 05:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teacherprofile_brand_alter_studentprofile_student_id'),
        ('quizzes', '0004_alter_answer_selected_choices_alter_quiz_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order in which this question appeared for the student.'),
        ),
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the choice. Allowed formats: jpg, jpeg, png.', null=True, upload_to='choice_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='The order of the question in the quiz, set by the teacher.'),
        ),
        migrations.AddField(
            model_name='question',
            name='selection_type',
            field=models.CharField(choices=[('single', 'Single Correct Answer'), ('multiple', 'Multiple Correct Answers')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='question_order',
            field=models.CharField(choices=[('created', 'As created by teacher'), ('random', 'Randomly for each student')], default='created', help_text='The order in which questions are presented to the student.', max_length=10),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='are_answers_released',
            field=models.BooleanField(default=False, help_text='Manually released by teacher'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='is_score_released',
            field=models.BooleanField(default=False, help_text='Manually released by teacher'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, help_text='Selected choices for the question', related_name='answers', to='quizzes.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='The question this choice belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, help_text='The choice text. Can be blank if an image is provided.', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the question. Allowed formats: jpg, jpeg, png.', null=True, upload_to='question_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='The question content. Can be blank if an image is provided.'),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='timer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes (0 = no time limit)', validators=[django.core.validators.MaxValueValidator(1440, message='Timer cannot exceed one day (1440 minutes).')]),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('quiz', 'student')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='quizzes_que_created_0b9a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_at'], name='quizzes_qui_created_48c994_idx'),
        ),
        migrations.AddIndex(
            model_name='quizcenter',
            index=models.Index(fields=['open_date'], name='quizzes_qui_open_da_4c4f60_idx'),
        ),
        migrations.AddIndex(
            model_name='quizcenter',
            index=models.Index(fields=['close_date'], name='quizzes_qui_close_d_0ebea4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['start_time'], name='quizzes_qui_start_t_18866f_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['student', 'quiz'], name='quizzes_qui_student_f14f45_idx'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
